export default class Currency {
    private code: string;

    private currencies: Array<{code: string, name: string}> = [
        {code: "AFN", name: "Afegane"},
        {code: "MGA", name: "Ariary"},
        {code: "PAB", name: "Balboa"},
        {code: "THB", name: "Baht"},
        {code: "ETB", name: "Birr etíope"},
        {code: "VES", name: "Bolivar Soberano Venezuelano"},
        {code: "BOB", name: "Boliviano"},
        {code: "GHS", name: "Cedi"},
        {code: "CRC", name: "Colon da Costa Rica"},
        {code: "SVC", name: "Colon de El Salvador"},
        {code: "NIO", name: "Cordoba Ouro"},
        {code: "DKK", name: "Coroa dinamarquesa"},
        {code: "ISK", name: "Coroa islandesa"},
        {code: "NOK", name: "Coroa norueguesa"},
        {code: "SEK", name: "Coroa sueca"},
        {code: "CZK", name: "Coroa tcheca"},
        {code: "GMD", name: "Dalasi"},
        {code: "DZD", name: "Dinar argelino"},
        {code: "RSD", name: "Dinar sérvio"},
        {code: "BHD", name: "Dinar do Bahrein"},
        {code: "IQD", name: "Dinar iraquiano"},
        {code: "JOD", name: "Dinar jordaniano"},
        {code: "KWD", name: "Dinar do Kuwait"},
        {code: "LYD", name: "Dinar da Líbia"},
        {code: "MKD", name: "Dinar macedonio"},
        {code: "TND", name: "Dinar tunisiano"},
        {code: "XDR", name: "Direito especial de saque"},
        {code: "AED", name: "Dirham dos Emirados Árabes Unidos"},
        {code: "MAD", name: "Dirham marroquino"},
        {code: "STN", name: "Dobra São Tomé"},
        {code: "AUD", name: "Dólar australiano"},
        {code: "BND", name: "Dólar do Brunei"},
        {code: "CAD", name: "Dólar canadense"},
        {code: "XCD", name: "Dólar do Caribe Oriental"},
        {code: "KYD", name: "Dólar das Ilhas Cayman"},
        {code: "SGD", name: "Dólar de Cingapura"},
        {code: "GYD", name: "Dólar da Guiana"},
        {code: "NAD", name: "Dólar da Namíbia"},
        {code: "SBD", name: "Dólar das Ilhas Salomão"},
        {code: "SRD", name: "Dólar do Suriname"},
        {code: "USD", name: "Dólar dos Estados Unidos"},
        {code: "FJD", name: "Dólar de Fiji"},
        {code: "HKD", name: "Dólar de Hong Kong"},
        {code: "LRD", name: "Dólar da Libéria"},
        {code: "NZD", name: "Dólar da Nova Zelândia"},
        {code: "ZWL", name: "Dolar do Zimbabue"},
        {code: "BSD", name: "Dólar das Bahamas"},
        {code: "BBD", name: "Dólar de Barbados"},
        {code: "BZD", name: "Dólar do Belize"},
        {code: "BMD", name: "Dólar de Bermuda"},
        {code: "JMD", name: "Dólar jamaicano"},
        {code: "TTD", name: "Dólar de Trindade e Tobago"},
        {code: "VND", name: "Dong"},
        {code: "AMD", name: "Dram"},
        {code: "CVE", name: "Escudo cabo-verdiano"},
        {code: "EUR", name: "Euro"},
        {code: "AWG", name: "Florim de Aruba"},
        {code: "HUF", name: "Forint"},
        {code: "XOF", name: "Franco CFA BCEAO"},
        {code: "XAF", name: "Franco CFA BEAC"},
        {code: "XPF", name: "Franco CFP"},
        {code: "KMF", name: "Franco das Comores"},
        {code: "CDF", name: "Franco congolês"},
        {code: "CHF", name: "Franco suíço"},
        {code: "BIF", name: "Franco do Burundi"},
        {code: "DJF", name: "Franco do Djibuti"},
        {code: "GNF", name: "Franco da Guiné"},
        {code: "RWF", name: "Franco de Ruanda"},
        {code: "HTG", name: "Gourde"},
        {code: "PYG", name: "Guarani"},
        {code: "ANG", name: "Florim"},
        {code: "UAH", name: "Grívnia"},
        {code: "JPY", name: "Iene"},
        {code: "PGK", name: "Kina"},
        {code: "AOA", name: "Kwanza"},
        {code: "GEL", name: "Lari"},
        {code: "ALL", name: "Lek"},
        {code: "HNL", name: "Lempira"},
        {code: "SLL", name: "Leone"},
        {code: "MDL", name: "Leu da Moldávia"},
        {code: "BGN", name: "Lev"},
        {code: "GIP", name: "Libra de Gibraltar"},
        {code: "SHP", name: "Libra de Santa Helena"},
        {code: "GBP", name: "Libra Esterlina"},
        {code: "SSP", name: "Libra Sul Sudanesa"},
        {code: "EGP", name: "Libra egípcia"},
        {code: "FKP", name: "Libra das Malvinas"},
        {code: "LBP", name: "Libra libanesa"},
        {code: "SYP", name: "Libra da Síria"},
        {code: "SZL", name: "Lilangeni"},
        {code: "TRY", name: "Lira turca"},
        {code: "LSL", name: "Loti"},
        {code: "AZN", name: "Manat do Azerbaijão"},
        {code: "BAM", name: "Marco conversível"},
        {code: "NGN", name: "Naira"},
        {code: "ERN", name: "Nakfa"},
        {code: "BTN", name: "Ngultrum"},
        {code: "SDG", name: "Nova libra sudanesa"},
        {code: "MZN", name: "Metical"},
        {code: "TWD", name: "Novo Dólar de Taiwan"},
        {code: "RON", name: "Leu romeno"},
        {code: "TMT", name: "Manat turcomano"},
        {code: "PEN", name: "Novo sol"},
        {code: "XAU", name: "Ouro"},
        {code: "TOP", name: "Paanga"},
        {code: "MOP", name: "Pataca"},
        {code: "ARS", name: "Peso argentino"},
        {code: "CLP", name: "Peso chileno"},
        {code: "COP", name: "Peso colombiano"},
        {code: "CUP", name: "Peso cubano"},
        {code: "PHP", name: "Peso filipino"},
        {code: "MXN", name: "Peso mexicano"},
        {code: "DOP", name: "Peso dominicano"},
        {code: "UYU", name: "Peso Uruguaio"},
        {code: "BWP", name: "Pula"},
        {code: "ZMW", name: "Kwacha de Zambia"},
        {code: "MWK", name: "Kwacha de Malavi"},
        {code: "GTQ", name: "Quetzal guatemalteco"},
        {code: "MMK", name: "Kyat"},
        {code: "LAK", name: "Kip"},
        {code: "ZAR", name: "Rand"},
        {code: "BRL", name: "Real"},
        {code: "CNY", name: "Renminbi"},
        {code: "CNH", name: "Renminbi Hong Kong"},
        {code: "SAR", name: "Rial saudita"},
        {code: "QAR", name: "Rial do Qatar"},
        {code: "YER", name: "Rial do Iêmen"},
        {code: "IRR", name: "Rial iraniano"},
        {code: "OMR", name: "Rial Omã"},
        {code: "KHR", name: "Riel"},
        {code: "MYR", name: "Ringgit"},
        {code: "BYN", name: "RUBLO BIELORRUSSO"},
        {code: "RUB", name: "Rublo"},
        {code: "MVR", name: "Rufia maldivense"},
        {code: "SCR", name: "Rupia das Seychelles"},
        {code: "INR", name: "Rupia indiana"},
        {code: "IDR", name: "Rupia indonésia"},
        {code: "MUR", name: "Rupia de Maurício"},
        {code: "NPR", name: "Rupia nepalesa"},
        {code: "PKR", name: "Rupia paquistanesa"},
        {code: "LKR", name: "Rupia do Sri Lanka"},
        {code: "ILS", name: "Shekel"},
        {code: "KGS", name: "Som"},
        {code: "UZS", name: "Som Uzbeque"},
        {code: "TJS", name: "Somoni"},
        {code: "BDT", name: "Taka"},
        {code: "WST", name: "Tala"},
        {code: "KZT", name: "Tenge"},
        {code: "MNT", name: "Tugrik"},
        {code: "MRU", name: "Ouguiya"},
        {code: "MRO", name: "Ouguiya"},
        {code: "XEU", name: "Unidade monetária européia"},
        {code: "CLF", name: "Unidade de fomento do chile"},
        {code: "COU", name: "UVR"},
        {code: "VUV", name: "Vatu"},
        {code: "KRW", name: "Won sul coreano"},
        {code: "KPW", name: "Won norte coreano"},
        {code: "TZS", name: "Xelim da Tanzânia"},
        {code: "KES", name: "Xelim queniano"},
        {code: "SOS", name: "Xelim somali"},
        {code: "UGX", name: "Xelim de Uganda"},
        {code: "PLN", name: "Zloty"},
    ];

    constructor(code: string) {

        if (!this.currencies.find(item => item.code === code)) {
            throw new Error("Could not parse this currency");
        }

        this.code = code;
    }

    getCode() {
        return this.code;
    }
}